75 auth window change
SUAI-TaskPlanner-Contest/TaskPlanner pull request #79
Opened 2023-05-24 10:54 UTC by pavelparfishov

<html>
<body>
<h2 dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; font-size: 1.5em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Task merge request</h2>

Related Issue | [Изменить окно авторизации#75](https://github.com/SUAI-TaskPlanner-Contest/TaskPlanner/issues/75)
-- | --
Квалификация ревьюера | Знание требований заказчика

Исполнители: @pavelparfishov

<h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></h3><h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a id="user-content-code-changes" class="anchor" aria-hidden="true" href="https://github.com/SUAI-TaskPlanner-Contest/TaskPlanner/blob/main/Workflow%20Guides/Templates/MrMessage.md#code-changes" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; float: left; padding-right: 4px; margin-left: -20px; line-height: 1;"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z"></path></svg>

</a>Code changes</h3> Был изменен QML-код для окна авторизации: добавлены новые шрифты, изменены цвета и дизайн.  Еще были добавлены обработчики нажатия на кнопки и изменение цвета кнопки при нажатии для визуального удобства.

<h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a id="user-content-ui-demonstration" class="anchor" aria-hidden="true" href="https://github.com/SUAI-TaskPlanner-Contest/TaskPlanner/blob/main/Workflow%20Guides/Templates/MrMessage.md#ui-demonstration" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; float: left; padding-right: 4px; margin-left: -20px; line-height: 1;"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z"></path></svg>
</a>UI Demonstration</h3>

![image](https://github.com/SUAI-TaskPlanner-Contest/TaskPlanner/assets/78814540/4c23e8ee-0f5b-4025-b911-cc3fc74be791)

<h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 0px !important; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a id="user-content-how-to-test" class="anchor" aria-hidden="true" href="https://github.com/SUAI-TaskPlanner-Contest/TaskPlanner/blob/main/Workflow%20Guides/Templates/MrMessage.md#how-to-test" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; float: left; padding-right: 4px; margin-left: -20px; line-height: 1;"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z"></path></svg>
</a>How to test</h3> <p>Проверить наличие необходимых полей и визуальную привлекательность окна. Также проверить корректность конструкций на Python</p>

</body>
</html>

2023-05-24 17:30 UTC, astronik00 commented on Code/Auth_window/main.py
> +        print("Local area clicked")
Такие же замечания, как в #66
Убрать print, оставить pass

2023-05-25 11:03 UTC, astronik00 commented on Code/Auth_window/window.qml
> +    flags: Qt.FramelessWindowHint // Установите флаг для отображения окна без системной строки
этого комментария не должно быть в мейне

2023-05-25 11:03 UTC, astronik00 commented on Code/Auth_window/window.qml
> +        palette.buttonText: "white"
если код не используется, то лучше его убрать, либо пометить, зачем он может быть нужен

2023-05-25 18:59 UTC, pavelparfishov commented on Code/Auth_window/window.qml
> +        palette.buttonText: "white"
@astronik00 Вроде все лишнее везде убрал. Добавил файл с примерами использования [Readme.md](https://github.com/SUAI-TaskPlanner-Contest/TaskPlanner/blob/75-auth-window-change/Code/Auth_window/Readme.md)

2023-05-26 15:41 UTC, pavelparfishov commented
@astronik00  изменил окно после ознакомления с окном Ярослава

![image](https://github.com/SUAI-TaskPlanner-Contest/TaskPlanner/assets/78814540/15a2bb02-8cb7-45d0-b261-ccbdc308b34b)

2023-05-26 16:28 UTC, astronik00 requested changes
В целом все хорошо, вот мои последние замечания. Также попробуй сделать squash, чтобы все было теперь одним коммитом. Если не получается - пиши, я помогу.

2023-05-26 16:28 UTC, astronik00 commented on Code/Auth_window/main.py
> +        pass
Также этот класс нужно вынести в отдельный файл. И это не ButtonHandler, а тогда AuthWindowHandler, ибо обрабатывает он все окно, а не конкретно кнопки. В файле main.py находится только вызов твоего окна авторизации, в общем какие-то глобальные вещи. Все детали реализации должны быть вынесены.

2023-05-26 16:28 UTC, astronik00 commented on Code/Auth_window/main.py
> +    engine.rootContext().setContextProperty("buttonHandler", buttonHandler)
эти 2 строки можно в 1 сократить, ибо больше объект нигде не используется

2023-05-30 12:45 UTC, pavelparfishov commented on Code/Auth_window/main.py
> +        pass
@astronik00 Вынес класс в отдельный файл. Сделал squash. Вроде получилось

2023-06-01 13:30 UTC, pavelparfishov commented
@astronik00 удалил лишнюю папку с AuthWindow. Убрал синее свечение при наведении на кнопку. Проверил вывод окна с помощью кода из инструкции - работает
![image](https://github.com/SUAI-TaskPlanner-Contest/TaskPlanner/assets/78814540/4e65b392-8312-4aaa-9f8c-3a05659751cf)

2023-06-04 08:03 UTC, merged